## Import Packages

In [4]:
import pandas as pd
import numpy as np
import plotly.express as px
import form4_common as f4

pd.set_option("display.max_columns", 100)

## Data Import

In [5]:
df = pd.read_pickle(f"{f4.data_output}/ceo_purchases.pkl")
display(df.shape, df.head(2))

(201432, 22)

,date,date_filed,shares,price_per_share,transaction_value,transaction_code,ticker,company_name,director,position,title_of_security,ownership_form,market,market_cap,source_url,accession,is_10b5_1_plan,footnotes,shares_owned_after,pct_of_holdings,cluster_buy_count,is_cluster_buy
0,2026-07-23,2026-07-23,200.0,184.3300,36866.000,Sell,PSMT,PRICESMART INC,Bahrambeygui Sherry S.,Director,"Common Stock, $0.0001 par value per share",Direct,NASDAQ,5.710894e+09,https://www.sec.gov/Archives/edgar/data/104180...,0001628280-26-049447,False,The reported securities are owned directly or ...,38749.0,0.005135,NaN,NaN
1,2026-07-21,2026-07-23,64730.0,78.3441,5071213.593,Sell,CRWV,"CoreWeave, Inc.",Intrator Michael N,CEO and President,Class A Common Stock,Direct,NASDAQ,3.997939e+10,https://www.sec.gov/Archives/edgar/data/176962...,0001769628-26-000327,True,The reported transaction represents a sale eff...,2545916.0,0.024795,NaN,NaN

In [9]:
results_df = pd.read_pickle(f"{f4.data_output}/backtest_results.pkl")
display(results_df.shape, results_df.head(2))

(31537, 33)

,accession,ticker,director,position,market_cap,position_bucket,transaction_code,date_filed,transaction_value,pct_of_holdings,pct_of_holdings_bucket,ownership_form,cluster_buy_count,is_cluster_buy,is_10b5_1_plan,is_10b5_1_bucket,entry_date,entry_price,raw_return_5d,benchmark_return_5d,abnormal_return_5d,raw_return_10d,benchmark_return_10d,abnormal_return_10d,raw_return_20d,benchmark_return_20d,abnormal_return_20d,raw_return_60d,benchmark_return_60d,abnormal_return_60d,raw_return_120d,benchmark_return_120d,abnormal_return_120d
0,0001567619-23-001134,AAME,ROBINSON HARRIETT J,10% Owner,3.202365e+07,10% Owner,Buy,2023-01-23,900000.00,0.361333,20-50%,Direct,0.0,False,NaN,Unknown,2023-01-24,2.461385,-0.015686,0.024916,-0.040602,-0.011765,0.071739,-0.083504,-0.058823,0.018061,-0.076884,-0.082353,0.066941,-0.149294,-0.270588,0.269904,-0.540493
1,0001683168-25-006247,AAOI,Lin Che-Wei,Director,8.868430e+09,Director,Buy,2025-08-15,99738.76,0.018518,<5%,Direct,3.0,True,False,Discretionary,2025-08-18,22.780001,0.068481,-0.007750,0.076231,0.025022,-0.015598,0.040620,0.269974,0.033175,0.236799,0.042581,0.085650,-0.043069,1.103161,0.075027,1.028133

In [7]:
signal_regression_results = pd.read_pickle(f"{f4.data_output}/signal_regression_results.pkl")
display(signal_regression_results.shape, signal_regression_results.head(2))

(80, 8)

,holding_days,n,term,coef,std_err_clustered,t_stat_clustered,p_value_clustered,r_squared
0,5,31174,Intercept,0.011789,0.012244,0.962846,0.335625,0.009628
1,5,31174,is_cluster_buy[T.True],0.011599,0.005084,2.281611,0.022512,0.009628

## Data Exploration

In [8]:
results_df[results_df['ticker'] == 'VCIG']

,accession,ticker,director,position,position_bucket,transaction_code,date_filed,transaction_value,pct_of_holdings,pct_of_holdings_bucket,ownership_form,cluster_buy_count,is_10b5_1_plan,is_10b5_1_bucket,entry_date,entry_price,raw_return_5d,benchmark_return_5d,abnormal_return_5d,raw_return_10d,benchmark_return_10d,abnormal_return_10d,raw_return_20d,benchmark_return_20d,abnormal_return_20d,raw_return_60d,benchmark_return_60d,abnormal_return_60d,raw_return_120d,benchmark_return_120d,abnormal_return_120d
29919,0001213900-26-061239,VCIG,HOO VOON HIM,CEO and Director,Other Officer,Buy,2026-05-27,869999.55,0.416276,20-50%,Direct,0.0,False,Discretionary,2026-05-28,3.750,1.200000,0.005412,1.194588,0.522667,-0.032858,0.555525,-0.160000,-0.052045,-0.107955,NaN,NaN,NaN,NaN,NaN,NaN
29920,0001213900-26-060307,VCIG,HOO VOON HIM,CEO and Director,Other Officer,Buy,2026-05-22,900000.00,3.231035,50%+,Direct,0.0,False,Discretionary,2026-05-26,1.655,4.432024,0.018932,4.413093,2.649547,-0.034286,2.683833,1.719033,-0.041889,1.760923,NaN,NaN,NaN,NaN,NaN,NaN

In [18]:
df[df['ticker'] == 'INLF'].sort_values(by='date_filed')

,date,date_filed,shares,price_per_share,transaction_value,transaction_code,ticker,company_name,director,position,title_of_security,ownership_form,market,market_cap,source_url,accession,is_10b5_1_plan,footnotes,shares_owned_after,pct_of_holdings,cluster_buy_count,is_cluster_buy
4145,2026-06-24,2026-06-29,948910.0,0.043,40803.130,Buy,INLF,INLIF Ltd,HRT FINANCIAL LP,10% Owner,Common Stock,Direct,NASDAQ,222279.821975,https://www.sec.gov/Archives/edgar/data/199159...,0001475597-26-000115,False,NaN,1858061.0,1.043732,0.0,False
4258,2026-06-25,2026-06-29,1781958.0,0.030,53458.740,Buy,INLF,INLIF Ltd,HRT FINANCIAL LP,10% Owner,Common Stock,Direct,NASDAQ,222279.821975,https://www.sec.gov/Archives/edgar/data/199159...,0001475597-26-000115,False,NaN,3640019.0,0.959042,0.0,False
4367,2026-06-26,2026-06-29,1689946.0,0.056,94636.976,Buy,INLF,INLIF Ltd,HRT FINANCIAL LP,10% Owner,Common Stock,Direct,NASDAQ,222279.821975,https://www.sec.gov/Archives/edgar/data/199159...,0001475597-26-000115,False,NaN,5329965.0,0.464268,0.0,False
3452,2026-06-29,2026-07-01,2919237.0,0.064,186831.168,Buy,INLF,INLIF Ltd,HRT FINANCIAL LP,10% Owner,Common Stock,Direct,NASDAQ,216757.347242,https://www.sec.gov/Archives/edgar/data/199159...,0001475597-26-000122,False,NaN,8249202.0,0.547703,0.0,False
3673,2026-06-30,2026-07-01,3831240.0,0.057,218380.680,Sell,INLF,INLIF Ltd,HRT FINANCIAL LP,10% Owner,Common Stock,Direct,NASDAQ,216757.347242,https://www.sec.gov/Archives/edgar/data/199159...,0001475597-26-000122,False,NaN,4417962.0,0.464438,NaN,NaN
3303,2026-07-01,2026-07-02,3691666.0,0.034,125516.644,Sell,INLF,INLIF Ltd,HRT FINANCIAL LP,10% Owner,Common Stock,Direct,NASDAQ,216757.347242,https://www.sec.gov/Archives/edgar/data/199159...,0001475597-26-000127,False,NaN,726296.0,0.835604,NaN,NaN

In [13]:
results_df[results_df['ticker'] == 'INLF'].sort_values(by = 'entry_date', ascending = True)

,accession,ticker,director,position,market_cap,position_bucket,transaction_code,date_filed,transaction_value,pct_of_holdings,pct_of_holdings_bucket,ownership_form,cluster_buy_count,is_cluster_buy,is_10b5_1_plan,is_10b5_1_bucket,entry_date,entry_price,raw_return_5d,benchmark_return_5d,abnormal_return_5d,raw_return_10d,benchmark_return_10d,abnormal_return_10d,raw_return_20d,benchmark_return_20d,abnormal_return_20d,raw_return_60d,benchmark_return_60d,abnormal_return_60d,raw_return_120d,benchmark_return_120d,abnormal_return_120d
15417,0001475597-26-000115,INLF,HRT FINANCIAL LP,10% Owner,222279.821975,10% Owner,Buy,2026-06-29,40803.130,1.043732,50%+,Direct,0.0,False,False,Discretionary,2026-06-30,12.4,-0.684677,0.001788,-0.686466,-0.779032,0.017222,-0.796255,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15418,0001475597-26-000115,INLF,HRT FINANCIAL LP,10% Owner,222279.821975,10% Owner,Buy,2026-06-29,53458.740,0.959042,50%+,Direct,0.0,False,False,Discretionary,2026-06-30,12.4,-0.684677,0.001788,-0.686466,-0.779032,0.017222,-0.796255,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15419,0001475597-26-000115,INLF,HRT FINANCIAL LP,10% Owner,222279.821975,10% Owner,Buy,2026-06-29,94636.976,0.464268,20-50%,Direct,0.0,False,False,Discretionary,2026-06-30,12.4,-0.684677,0.001788,-0.686466,-0.779032,0.017222,-0.796255,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15416,0001475597-26-000122,INLF,HRT FINANCIAL LP,10% Owner,216757.347242,10% Owner,Buy,2026-07-01,186831.168,0.547703,50%+,Direct,0.0,False,False,Discretionary,2026-07-02,6.0,-0.428333,0.008992,-0.437326,-0.570000,-0.020238,-0.549762,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [19]:
results_df.sort_values(by='market_cap', ascending = True).head(10)

,accession,ticker,director,position,market_cap,position_bucket,transaction_code,date_filed,transaction_value,pct_of_holdings,pct_of_holdings_bucket,ownership_form,cluster_buy_count,is_cluster_buy,is_10b5_1_plan,is_10b5_1_bucket,entry_date,entry_price,raw_return_5d,benchmark_return_5d,abnormal_return_5d,raw_return_10d,benchmark_return_10d,abnormal_return_10d,raw_return_20d,benchmark_return_20d,abnormal_return_20d,raw_return_60d,benchmark_return_60d,abnormal_return_60d,raw_return_120d,benchmark_return_120d,abnormal_return_120d
20899,0001777051-23-000002,NUWE,Jaramillo Nestor Jr.,President and CEO,189012.045604,President,Buy,2023-03-16,19629.420,NaN,Unknown,Direct,0.0,False,NaN,Unknown,2023-03-17,238728.000000,0.047414,0.010911,0.036503,0.047414,0.044935,0.002479,-0.012931,0.039447,-0.052378,-0.364224,0.160476,-0.524700,-0.586207,0.176567,-0.762774
15416,0001475597-26-000122,INLF,HRT FINANCIAL LP,10% Owner,216757.347242,10% Owner,Buy,2026-07-01,186831.168,0.547703,50%+,Direct,0.0,False,False,Discretionary,2026-07-02,6.000000,-0.428333,0.008992,-0.437326,-0.570000,-0.020238,-0.549762,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15418,0001475597-26-000115,INLF,HRT FINANCIAL LP,10% Owner,222279.821975,10% Owner,Buy,2026-06-29,53458.740,0.959042,50%+,Direct,0.0,False,False,Discretionary,2026-06-30,12.400000,-0.684677,0.001788,-0.686466,-0.779032,0.017222,-0.796255,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15417,0001475597-26-000115,INLF,HRT FINANCIAL LP,10% Owner,222279.821975,10% Owner,Buy,2026-06-29,40803.130,1.043732,50%+,Direct,0.0,False,False,Discretionary,2026-06-30,12.400000,-0.684677,0.001788,-0.686466,-0.779032,0.017222,-0.796255,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15419,0001475597-26-000115,INLF,HRT FINANCIAL LP,10% Owner,222279.821975,10% Owner,Buy,2026-06-29,94636.976,0.464268,20-50%,Direct,0.0,False,False,Discretionary,2026-06-30,12.400000,-0.684677,0.001788,-0.686466,-0.779032,0.017222,-0.796255,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30397,0001209191-23-020480,VYNE,LEPORE PATRICK G,Director,339859.811229,Director,Buy,2023-03-22,49680.000,5.760369,50%+,Direct,1.0,True,False,Discretionary,2023-03-23,2.600000,0.161538,0.017115,0.144424,0.046154,0.023422,0.022732,0.596154,0.022109,0.574045,0.926923,0.157135,0.769788,0.488462,0.179043,0.309419
30396,0001209191-23-055787,VYNE,LEPORE PATRICK G,Director,339859.811229,Director,Buy,2023-11-17,50778.000,0.553851,50%+,Direct,0.0,False,False,Discretionary,2023-11-20,4.000000,0.000000,0.010401,-0.010401,-0.127500,0.006732,-0.134232,-0.377500,0.061442,-0.438942,-0.432500,0.116090,-0.548590,-0.277500,0.168127,-0.445627
30398,0001209191-23-020477,VYNE,Harsch Mutya,Chief Legal Officer and GC,339859.811229,Other Officer,Buy,2023-03-22,25000.000,0.786102,50%+,Direct,1.0,True,False,Discretionary,2023-03-23,2.600000,0.161538,0.017115,0.144424,0.046154,0.023422,0.022732,0.596154,0.022109,0.574045,0.926923,0.157135,0.769788,0.488462,0.179043,0.309419
14089,0001213900-26-059540,HAO,Fan Zhen,CEO & Chairman,354493.381859,Chair,Buy,2026-05-20,720000.000,57.903880,50%+,Direct,0.0,False,False,Discretionary,2026-05-21,1.630000,-0.355828,0.031709,-0.387538,-0.457055,-0.016608,-0.440447,-0.312883,0.000879,-0.313762,NaN,NaN,NaN,NaN,NaN,NaN
13504,0000897069-23-001807,GIPR,Quilty Patrick,NaN,542502.406074,Unknown,Buy,2023-12-20,1980.000,0.021790,<5%,Direct,0.0,False,False,Discretionary,2023-12-21,37.038645,0.005089,0.005911,-0.000822,0.035624,-0.005319,0.040942,0.024471,0.033693,-0.009222,-0.016520,0.096915,-0.113435,0.101552,0.185332,-0.083780